"use strict";
const $ = (s) => document.querySelector(s);
let projects = [], selected = null, area = "shared", activeProject = null, loadGeneration = 0;
const labels = {faustus:"Faustus",writer:"Writer",lumiere:"Lumiere",prospero:"Prospero",borges:"Borges",kafka:"Kafka",daguerre:"Daguerre",scheherazade:"Scheherazade"};
const appName = (id) => labels[id] || id;
const node = (tag, text, cls) => {const e=document.createElement(tag); if(text!==undefined)e.textContent=text; if(cls)e.className=cls; return e;};
function message(text, error=false) {const el=$("#message");el.textContent=text;el.dataset.error=String(error);el.hidden=!text;}
async function api(path, body) {const res=await fetch(path,{method:body?"POST":"GET",credentials:"same-origin",headers:body?{"Content-Type":"application/json"}:{},body:body?JSON.stringify(body):undefined});const result=await res.json();if(!res.ok||result.ok===false)throw new Error(result.error||"Atlas no pudo completar la operación. Prueba de nuevo.");return result.result||result;}
const call=(name,arguments_)=>api("/api/agent/call",{name:`atlas_${name}`,arguments:arguments_});
async function copy(value) {try{await navigator.clipboard.writeText(value);message("Ruta copiada. Puedes usarla en cualquier aplicación del proyecto.");}catch(e){message("No se pudo copiar. Selecciona la ruta y cópiala con Ctrl+C.",true);}}
function button(text, action, cls) {const b=node("button",text,cls);b.type="button";b.addEventListener("click",action);return b;}
function projectNavigation() {const nav=$("#projects");nav.replaceChildren();for(const p of projects){const b=button(p.name,()=>choose(p.id));b.setAttribute("aria-current",String(p.id===selected));b.append(node("small",p.sphere==="work"?"Trabajo":p.sphere==="freelance"?"Autónomo":"Personal"));nav.append(b);}if(!projects.length)nav.append(node("p","Todavía no hay proyectos.","muted"));}
async function choose(id) {selected=id;area="shared";projectNavigation();await showProject();}
async function showProject() {if(!selected)return;const requestedId=selected,generation=++loadGeneration;activeProject=null;const loading=node("section",undefined,"empty");loading.append(node("h2","Cargando archivos del proyecto…"));$("#main").replaceChildren(loading);$("#main").setAttribute("aria-busy","true");try{const view=await call("project",{project_id:requestedId});if(generation!==loadGeneration||selected!==requestedId)return;activeProject=view.project;render(view);}catch(e){if(generation===loadGeneration&&selected===requestedId){loading.replaceChildren(node("p","No se pudo abrir el proyecto. Selecciónalo de nuevo para reintentar."));message(e.message,true);}}finally{if(generation===loadGeneration)$("#main").removeAttribute("aria-busy");}}
function icon() {const svg=document.createElementNS("http://www.w3.org/2000/svg","svg");svg.setAttribute("viewBox","0 0 24 28");svg.setAttribute("aria-hidden","true");const path=document.createElementNS(svg.namespaceURI,"path");path.setAttribute("d","M5 2h9l5 5v19H5z M14 2v6h5 M8 13h8 M8 17h8 M8 21h5");svg.append(path);return svg;}
function render(view) {const main=$("#main");main.replaceChildren();const p=view.project;const title=node("section",undefined,"project-title");title.append(node("h2",p.name));if(p.goal)title.append(node("p",p.goal));if(p.state==="archived")title.append(node("p","Proyecto archivado; sus archivos se conservan.","state"));main.append(title);
const folders=node("nav",undefined,"folders");folders.setAttribute("aria-label","Carpetas del proyecto");for(const [key,label] of [["shared","Compartidos"],...p.members.map(a=>[a,appName(a)])]){const b=button(label,()=>{area=key;render(view);});b.setAttribute("aria-pressed",String(area===key));folders.append(b);}main.append(folders);
const folder=area==="shared"?p.shared_path:p.hoard_paths[area];const location=node("section",undefined,"location");location.setAttribute("aria-label","Ruta de la carpeta seleccionada");location.append(node("p",folder,"path"),button("Copiar ruta",()=>copy(folder)));main.append(location);
const bar=node("div",undefined,"file-header");bar.append(node("h3",area==="shared"?"Archivos compartidos":`Archivos de ${appName(area)}`),button("Registrar archivo",()=>{$("#file-panel").hidden=!$("#file-panel").hidden;if(!$("#file-panel").hidden)$("#relative-path").focus();}));main.append(bar);
const filePanel=node("section",undefined,"file-form");filePanel.id="file-panel";filePanel.hidden=true;const form=node("form");const label=node("label","Archivo guardado dentro del proyecto");const input=node("input");input.id="relative-path";input.name="relative_path";input.required=true;input.placeholder=area==="shared"?"shared/portada.png":`hoards/${area}/proyecto`;label.append(input,node("small","Registra el archivo para compartir su ruta. Su contenido no se modifica."));const actions=node("div",undefined,"form-actions");const submit=node("button","Registrar");submit.type="submit";actions.append(submit,button("Cancelar",()=>{filePanel.hidden=true;},"quiet"));form.append(label,actions);form.addEventListener("submit",async e=>{e.preventDefault();submit.disabled=true;try{let relative=input.value.trim().replaceAll("\\","/");const base=p.path.replaceAll("\\","/")+"/";if(relative.toLowerCase().startsWith(base.toLowerCase()))relative=relative.slice(base.length);await call("file_register",{project_id:p.id,relative_path:relative,app:area==="shared"?p.owner:area});message("Archivo registrado. Los Hoards del proyecto usarán esta misma ruta.");await showProject();}catch(err){message(err.message,true);}finally{submit.disabled=false;}});filePanel.append(form);main.append(filePanel);
const prefix=area==="shared"?"shared/":`hoards/${area}/`;const files=view.files.filter(f=>f.relative_path.startsWith(prefix));if(files.length){const wrap=node("div",undefined,"table-wrap"),table=node("table"),head=node("thead"),hr=node("tr");for(const h of ["Archivo","Registrado por","Acceso"])hr.append(node("th",h));head.append(hr);table.append(head);const body=node("tbody");for(const f of files){const row=node("tr"),name=node("td"),line=node("div",undefined,"file-name");const details=node("div");details.append(node("strong",f.title),node("p",f.relative_path));if(!f.exists)details.append(node("p","El archivo no está en su ruta. Comprueba si lo has movido.","state"));line.append(icon(),details);name.append(line);const app=node("td",appName(f.app),"muted"),access=node("td");access.append(button("Copiar ruta",()=>copy(f.path)));row.append(name,app,access);body.append(row);}table.append(body);wrap.append(table);main.append(wrap);}else{const empty=node("section",undefined,"folder-empty");empty.append(node("h3","Esta carpeta está lista para usar"),node("p","Guarda aquí un PNG, un documento o el proyecto nativo de tu aplicación. Después regístralo para que los demás Hoards puedan encontrarlo."));main.append(empty);}
const members=node("section",undefined,"members");members.append(node("h3","Trabajan en este proyecto"),node("p",p.members.map(appName).join(" · ")),node("p","Los archivos compartidos son originales de trabajo. Si los editas en otra aplicación, el cambio se ve en la misma ruta."));main.append(members);}
async function refresh() {try{const status=await api("/api/status");projects=status.projects;$("#disk-root").textContent=status.root;projectNavigation();if(projects.length&&!selected)selected=projects[0].id;if(selected){projectNavigation();await showProject();}}catch(e){message("No se pudo leer el disco compartido. "+e.message,true);}}
$("#new-project").addEventListener("click",()=>{$("#create-panel").hidden=false;$("#create-form input").focus();});$("#cancel-create").addEventListener("click",()=>{$("#create-panel").hidden=true;});
$("#create-form").addEventListener("input",e=>{delete e.currentTarget.dataset.requestId;});
$("#create-form").addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,submit=form.querySelector('[type="submit"]');submit.disabled=true;try{const values=Object.fromEntries(new FormData(form));const members=[...new Set([values.owner.trim().toLowerCase(),...values.members.split(",").map(s=>s.trim().toLowerCase()).filter(Boolean)])];form.dataset.requestId ||= crypto.randomUUID();const result=await call("project_create",{name:values.name,owner:values.owner.trim().toLowerCase(),members,sphere:values.sphere,goal:values.goal,request_id:form.dataset.requestId});selected=result.project.id;area="shared";$("#create-panel").hidden=true;form.reset();delete form.dataset.requestId;message("Proyecto creado. Copia la ruta de su carpeta y empieza a guardar archivos allí.");await refresh();}catch(err){message(err.message,true);}finally{submit.disabled=false;}});
refresh();
